### ISSUE TITLE
Problems with Lexicon Alpha

### ISSUE THREAD

**Issue by Raptor48** [mdias/rs_asio#8] opened 2019-12-27 13:48 UTC
Hi! 
Please advise what to do. 
![Error](https://user-images.githubusercontent.com/59286124/71519409-7c2b3c80-28c8-11ea-8c84-095589451e0d.png)

[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/4005427/RS_ASIO-log.txt)
Thank you!

**Comment by mdias** [comment] 2019-12-27 15:19
Hello

It seems your audio interface is only accepting 24-bit aligned data, while this project currently requires 32-bit aligned data. Check if you have a control panel that allows you to change this, but it's possible that you don't.

It would be well within possibility to make RS-ASIO work for 24-bit and/or 16-bit aligned data devices, but I currently don't have access to any such device and so it would be very difficult to implement this blindly.

**Comment by Raptor48** [comment] 2019-12-27 15:25
The control panel does not have such a function, sadly. Well, thanks for the answer!

**Comment by mdias** [comment] 2019-12-27 15:38
No problem.
I might implement this in the future if I find a way to test it and some time.

**Comment by mdias** [comment] 2019-12-30 22:15
I'm reopening this issue as RS-ASIO should have support for this in the newest [preview release](https://github.com/mdias/rs_asio/releases/tag/v0.3.2).

Please test with that, but make sure to turn down your volume while testing in case it outputs audio garbage :)

**Comment by Raptor48** [comment] 2019-12-30 22:28
Great news! Testing as soon as possible.

**Comment by Raptor48** [comment] 2020-01-02 13:18
Unfortunately no changes.
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/4015943/RS_ASIO-log.txt)

**Comment by mdias** [comment] 2020-01-02 21:59
Oh... I forgot to remove some old logic testing for sample formats we didn't previously support...
Perhaps [this build](https://github.com/mdias/rs_asio/releases/tag/v0.3.4) fixes it?

**Comment by Raptor48** [comment] 2020-01-03 10:22
Another error =(
0.336 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt24LSB
0.336 [ERROR]    failed to initialize asio driver with requested format
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/4018748/RS_ASIO-log.txt)

**Comment by mdias** [comment] 2020-01-03 18:12
Disregard the IEEE Float message, that is not a fatal error, and it just means than while the game was negotiating an audio format with RS-ASIO, it told it "no" because we only accept 32-bit floating point formats if the audio interface supports it natively.

In fact, I can see that ASIO was actually streaming data, however you have you interface configured to use 512-sample size buffer, which is too much for Rocksmith. Please use something like 128.

If for some reason you can't access the control panel for it, use the following config in RS-ASIO.ini:
```
[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=custom
CustomBufferSize=128
```

Please post another log if it still fails, as you're the first user with ASIO drivers that ask for format ASIOSTInt24LSB and I implemented it blindly, as I don't have such an interface to test, but hopefuly it's working; just make sure to turn down your volume while testing :)

**Comment by Raptor48** [comment] 2020-01-04 10:06
Did as you said, Rocksmith starts without errors, but there is no sound :(
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/4021749/RS_ASIO-log.txt)

**Comment by SAARussian** [comment] 2020-01-04 10:07
@Raptor48 maybe alt+tab ? xD

**Comment by mdias** [comment] 2020-01-07 23:44
Please try [this release](https://github.com/mdias/rs_asio/releases/tag/v0.3.5) and post your new log please.
It won't fix the issue, but it adds some more logging that may be crucial to find what the issue is.

**Comment by Raptor48** [comment] 2020-01-08 19:30
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/4036904/RS_ASIO-log.txt)
Again I =), when I start Rocksmtih, I get noise or silence. I tried to do as you advised with "custom 128", nothing has changed. Here are the logs.

**Comment by mdias** [comment] 2020-01-08 21:54
Alright, here's a [new release](https://github.com/mdias/rs_asio/releases/tag/v0.3.6) to attempt fixing that. Fingers crossed :)

**Comment by mdias** [comment] 2020-01-10 01:22
There was a bug in the release linked above where input didn't work. Please download a newer release instead

**Closed** 2020-02-06 02:03 UTC
