### ISSUE TITLE
RS asks to check if Steam is running

### ISSUE THREAD

**Issue by Juppstein** [mdias/rs_asio#312] opened 2022-09-15 08:18 UTC
Honestly not sure if this is a problem of RS_ASIO or something else. I went back from the Beta version of RS to the regular one, put the new RS_ASIO files as well as the new D3D dll, I'm not using RSmods, in their place and started the game. I noticed a new DOS prompt popping up writing a patch progress (reported successful) and a message from RS suddenly appearing, asking to makes sure Steam is running. Never saw that window before.

I clicked OK on the window and the game continued to load. According to the RS_ASIO log the interface got detected and connected. Once in the game it suddenly asked me for login credentials to Uplay. After that it did not present me with my existing profile but it wanted me to create a new one. Getting a bit into panic mode, not wanting to really loose my profile, I Alt+F4'd out of the game. Looking at the game entry in Steam I saw that the game didn't go online since yesterday. So something must now have blocked access to Steam or Uplay. When I went back to the Steam Beta branch, including replacing the new dll and rs_asio files with the old ones, everything started to work again as usual.

Since I don't want to stay on that beta branch forever, you what's going on here?

**Comment by ciandial** [comment] 2022-09-15 08:29
Its Ubi added nuisance after patch, if you run the game from Rocksmith.exe in game directory.

Now you run the game from Steam or Steam executable with param:
steam://rungameid/221680 - [hyperlink type shortcut]
C:\Games\Steam\steam.exe -applaunch 221680 - [steam.exe type shortcut]

**Comment by Juppstein** [comment] 2022-09-15 09:06
> Its Ubi added nuisance after patch, if you run the game from Rocksmith.exe in game directory.
> 
> Now you run the game from Steam or Steam executable with param: steam://rungameid/221680 - [hyperlink type shortcut] C:\Games\Steam\steam.exe -applaunch 221680 - [steam.exe type shortcut]

Oi, that might be a proper problem for me. I run the whole thing in Linux. Ever since updating to Ubuntu 22.04 when I start from the Steam UI it will break the rs_asio / wineasio connection, making it impossible to establish a jack server connection. So far the only way I have found to make RS 2014 work is via Lutris by calling the exe directly without having a Steam UI interaction.

**Comment by mdias** [comment] 2022-09-15 10:35
If I launch the game on windows with steam closed, the popup also appears to me and the game is only launched once. Just like you described I was also presented with a screen without my profile.
Closing the game and opening it again through steam shows my profile once again.

So unfortunately the behavior you describe is apparently "working as intended" and not associated with any of the mods.

I'm not sure how the profiles are managed, so I can't really suggest anything that would guarantee you don't lose your profile.

**Comment by L0FKA** [comment] 2022-10-24 05:42
The profile is alright you shouldnt loose it since rsmods do backups for you, it just hints you to run through drm platform ofchoice for them, switch back to steam\applaunch and you're good to go, not relevant to rs asio. All rsasio could potentially cause is debugger present error from rocksmith.

You can close thia issue 🙂

**Closed** 2022-11-20 01:22 UTC
Labels: linux
