### ISSUE TITLE
Audio cuts out mid game with new patch on Focusrite Clarett 2Pre+

### ISSUE THREAD

**Issue by CosyConnoisseur** [mdias/rs_asio#315] opened 2022-09-24 20:57 UTC
Audio works for around 10 minutes before cutting out both game audio and the game receiving guitar input. Sometimes tabbing out and back in fixes it for another few minutes. Most times it leads to the game crashing. Happens on a fresh game install with just RS Asio using the same settings as pre patch. Reverted to the pre patch beta on Steam and using the January release or RS Asio and it works correctly again. 

Log is from an instance where I could alt tab the sound back in before quitting the game. 

[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/9639562/RS_ASIO-log.txt)

**Comment by mdias** [comment] 2022-09-25 16:18
Thank you for the report. I believe I've found the issue; please check this version 
[release-0.6.3-rc1.zip](https://github.com/mdias/rs_asio/files/9641222/release-0.6.3-rc1.zip)

**Comment by CosyConnoisseur** [comment] 2022-09-26 10:53
The audio doesn't seem to cut out now but there is no guitar audio or registering at all anymore. Also the game crashed on exit. I enabled the refcounthack which seemed to work for the crashing but the log seems to break at the end when I do it.

I'll give you two logs. One for each refcounthack setting. Just in case that's helpful.

[RS_ASIO-log 1.txt](https://github.com/mdias/rs_asio/files/9645459/RS_ASIO-log.1.txt) (refcounthack disabled)


[RS_ASIO-log 2.txt](https://github.com/mdias/rs_asio/files/9645462/RS_ASIO-log.2.txt) (refcounthack enabled)

**Comment by cedrick80** [comment] 2022-09-26 19:08
i have the same problem, i alredy update with 0.63 -rc1, i have no guitar audio or registered notes, the game dosnt crash anymore with the refcounthack enable.

**Comment by mdias** [comment] 2022-09-26 20:20
Thank you for the feedback. Can you please try this one? [release-0.6.3-rc2.zip](https://github.com/mdias/rs_asio/files/9649412/release-0.6.3-rc2.zip)

**Comment by cedrick80** [comment] 2022-09-26 21:20
ill try it when in home and report, thanks.

**Comment by cedrick80** [comment] 2022-09-27 00:24
i tried, still no sound from the guitar, by the way my interface is a UMC2.
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/9650441/RS_ASIO-log.txt)

**Comment by CosyConnoisseur** [comment] 2022-09-27 08:35
It's kind of back to the start now. It starts okay and I have guitar audio for a few minutes before losing all audio and crashing if I tab out and in. Game crashes on exit now no matter what I do with refcounthack. 
I tried using wasapi and that keeps game audio but I lose guitar audio as you'd probably expect. 

[RS_ASIO-log rc2.txt](https://github.com/mdias/rs_asio/files/9653488/RS_ASIO-log.rc2.txt)


[RS_ASIO-log rc2 wasapi.txt](https://github.com/mdias/rs_asio/files/9653489/RS_ASIO-log.rc2.wasapi.txt)

**Comment by mdias** [comment] 2022-09-27 19:07
@cedrick80 was it working for you with 0.5.9 and the pre-patch version of the game?
You also seem to be using WASAPI at the same time, which if using the same device as input may cause issues...

@CosyConnoisseur Are you able to try this on another machine?
If not I might be able to borrow a Focusrite from someone, but it may take a while.

**Comment by Noobonic** [comment] 2022-09-27 21:15
Same thing here with 0.63-r2. I'm on the latest steam version, not the pre-patch. I had to roll back to 0.60 since 0.61 causes audio drop outs sometimes as well along with crashing when you exit the game.

On 0.60 and prior, the game would start with audio when launched. 0.61 start up with audio like normal but then does what's described as above. 0.62 start with no audio and i have to click away and refocus to the window to get sound. then it loses it randomly.

**Comment by cedrick80** [comment] 2022-09-27 21:21
yeah, with the 0.5.9 it work well with the game prepatched. 
i dont have another cpu by the moment.

**Comment by mdias** [comment] 2022-09-27 21:41
@Noobonic so with 0.60 it's stable for you and audio doesn't drop out?
Also, can you tell me what interface you're using?

**Comment by Noobonic** [comment] 2022-09-27 21:45
Correct. Been stable like 0.59. No crashes, no drop outs and audio as soon as the game launches without needs to refocus the window.

I'm using an Antelope Audio Zen Go with with game in windowed mode (fullscreen doesn't fix any of the issues mentioned).

**Comment by mdias** [comment] 2022-09-27 23:16
Thank you!
I was able to reproduce the crashes after some fiddling and have a fix.
Also did some fixes to the buffer management, but in this case I'm not sure if it will fix the focusing issue or not; I'm kinda working in the dark on that specific issue.

Fingers crossed: [release-0.6.3-rc3.zip](https://github.com/mdias/rs_asio/files/9660129/release-0.6.3-rc3.zip)

@Noobonic I do notice your logs report a lot of buffer underruns, so you're probably running a buffer a bit too small for your configuration. I would think you can probably hear some crackling on the audio on that version.

**Comment by Noobonic** [comment] 2022-09-28 01:40
Happy to report 0.63 works fine with the issues I had. No drop outs, no crashing when quitting and no refocusing. 

In regards to my buffer setting, 64 samples is what I've been using for he longest while and didn't have any crackling in the game or while tracking in my DAW. However, I had to increase it to 128 samples with this build of rsasio. I'm guessing the changes you made borked that. But all good. Antelope makes good drivers, so the latency is still pretty low with my crappy laptop.

**Comment by mdias** [comment] 2022-09-28 01:59
Thank you for the update. 👍 

Indeed I didn't expect 0.63 to be slower than 0.60;; the opposite in fact due to a lot less log clutter during the buffer swaps.
I agree you probably just had something in the background and since you were already on the verge crackling, you just heard it.

I'm going to wait for the others to check too before creating an actual release.

**Comment by Noobonic** [comment] 2022-09-28 02:20
Here's the log if it helps;
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/9660894/RS_ASIO-log.txt)

**Comment by CosyConnoisseur** [comment] 2022-09-28 09:45
It's still not fixed for me with 6.3 rc3 I'm afraid. Noobonic gave me the idea to try each of the recent releases and I have narrowed it down to just 6.2. 6.1 and prior seem to work fine without problems or crashing so my issue has to be something changed in the latest release. I don't have another system handy right now but I will try it when I get a chance.

[RS_ASIO-log 61.txt](https://github.com/mdias/rs_asio/files/9663593/RS_ASIO-log.61.txt)

[RS_ASIO-log 62.txt](https://github.com/mdias/rs_asio/files/9663596/RS_ASIO-log.62.txt)

[RS_ASIO-log 63 rc3.txt](https://github.com/mdias/rs_asio/files/9663597/RS_ASIO-log.63.rc3.txt)

**Comment by CosyConnoisseur** [comment] 2022-09-28 11:59
I'm so confused now. I was sure it broke in the same way as usual. I must have made a mistake and not actually updated the dll or something. I just rechecked and it seems to work fine now. I don't know if it would even make a difference but after confirming 6.1 worked earlier, I installed RSMods and added some more cdlc and everything seems to work now and I don't know why! I'll keep checking and let you know if it comes back.

**Comment by mdias** [comment] 2022-09-28 13:30
Thank you for the feedback, I will for sure wait a bit more time before considering it stable enough for release.

**Comment by cedrick80** [comment] 2022-09-28 14:46
I tried yesterday with the 0.6.3, and was the same, only audio in the game but no guitar sound, I will try again when I get a chance and upload the log.

**Comment by mdias** [comment] 2022-09-28 16:49
@cedrick80 please do when able.

**Comment by SergeiZheleznov** [comment] 2022-09-28 18:43
I've tested 6.3-rc3 today with `MiniFuse ASIO Driver`. Here is the result
```
26.611 [INFO]  {ASIO IN 0} DebugWrapperAudioEndpointVolume::SetMasterVolumeLevelScalar fLevel: 0.17
26.611 [INFO]  {ASIO IN 0} DebugWrapperCaptureClient::GetBuffer
26.611 [INFO]  {ASIO IN 0} RSAsioAudioClient::SwapBuffers
26.611 [INFO]  {ASIO IN 0} DebugWrapperCaptureClient::ReleaseBuffer NumFramesRead: 64
26.612 [INFO]  {ASIO IN 0} DebugWrapperCaptureClient::GetBuffer
26.612 [INFO]  {ASIO IN 0} RSAsioAudioClient::SwapBuffers
26.612 [INFO]  {ASIO IN 0} DebugWrapperCaptureClient::ReleaseBuffer NumFramesRead: 64
26.614 [INFO]  {ASIO IN 0} DebugWrapperCaptureClient::GetBuffer
26.614 [INFO]  {ASIO IN 0} DebugWrapperCaptureClient::ReleaseBuffer NumFramesRead: 64
57.560 [INFO]  {ASIO Out} NotifyNewBuffer() - data discontinuity
86.553 [INFO]  {ASIO IN 0} NotifyNewBuffer() - data discontinuity
86.554 [INFO]  {ASIO Out} NotifyNewBuffer() - data discontinuity
161.737 [INFO]  {ASIO Out} NotifyNewBuffer() - data discontinuity
281.907 [INFO]  {ASIO IN 0} NotifyNewBuffer() - data discontinuity
281.907 [INFO]  {ASIO Out} NotifyNewBuffer() - data discontinuity
384.480 [INFO]  {ASIO Out} NotifyNewBuffer() - data discontinuity
421.867 [INFO]  {ASIO IN 0} NotifyNewBuffer() - data discontinuity
421.868 [INFO]  {ASIO Out} NotifyNewBuffer() - data discontinuity
422.067 [INFO]  {ASIO Out} NotifyNewBuffer() - data discontinuity
551.636 [INFO]  {ASIO Out} DebugWrapperAudioClient<struct IAudioClient3>::Stop
```
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/9668051/RS_ASIO-log.txt)

**Comment by mdias** [comment] 2022-09-28 19:20
@SergeiZheleznov have you tried 128 buffer size? 64 might be too small...
Did old releases show "buffer underrun" messages? If so, these are the same, perhaps I should rename them again...

Also, do you have any problems playing the game besides these messages?

**Comment by SergeiZheleznov** [comment] 2022-09-28 20:25
@mdias it's working without any issues with `256` buffer size. If it is more than that, then it starts to crackle. If the values are less, this leads to a crash. There are still a couple of errors in the log:
```
26.675 [INFO]  {ASIO IN 0} DebugWrapperDevice::Activate - Activate iid: IID_IAudioClient dwClsCtx: 17
26.675 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
26.675 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
26.675 [ERROR]    failed to initialize asio driver with requested format
26.675 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
26.675 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
26.675 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
26.675 [ERROR]    failed to initialize asio driver with requested format
26.675 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
26.675 [INFO]  {ASIO IN 0} DebugWrapperAudioClient<struct IAudioClient3>::IsFormatSupported - ShareMode: Exclusive
26.675 [ERROR]    rejecting IEEE Float as it's incompatible with current ASIO sample type ASIOSTInt32LSB
26.675 [ERROR]    failed to initialize asio driver with requested format
26.675 [INFO]    hr: AUDCLNT_E_UNSUPPORTED_FORMAT
```
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/9668667/RS_ASIO-log.txt)

**Comment by mdias** [comment] 2022-09-28 21:56
@SergeiZheleznov thank you for the feedback.

Seems like there might still be a couple more issues waiting to be found :/

**Comment by cedrick80** [comment] 2022-09-28 22:59
if i move the bufer below 256 there is no sound at all, with 256 i have game sound but no guitar sound, i still crash at exit. 

[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/9669349/RS_ASIO-log.txt)

**Comment by mdias** [comment] 2022-09-29 00:56
I managed to find more threading related issues, which explains some of the crashes that happen only to certain people and only with certain settings.
Please give this a try when able and if it freezes, crashes or has other sound issues please post the log of that run: [release-0.6.3-rc4.zip](https://github.com/mdias/rs_asio/files/9669786/release-0.6.3-rc4.zip)

@cedrick80 It's hard to say if this will help with your missing guitar sound. Did RS ASIO 0.5.9 work fine for you pre-patch?

@SergeiZheleznov I have issues myself with anything bigger than 256; I suspect this might be an issue with the game itself, but I'm not sure.
This RC4 patch should hopefuly fix the smaller buffers though.

**Comment by cedrick80** [comment] 2022-09-29 01:29
This RC4 version works well for me, same its has to be 256 buffer, and now i have both audio with no craking, no longer crash up at exit, thanks man.
[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/9670004/RS_ASIO-log.txt)

**Comment by TemugeB** [comment] 2022-09-29 17:32
Hi, thank for your great work. I was having the same issue with Focusrite scarlet solo but 0.6.3-rc4 seems to have solved the problem. Played for 2 hour without any sound cutting out.

**Comment by CosyConnoisseur** [comment] 2022-10-06 12:42
I did more testing and reconfirmed that rc3 broke audio the same way. It just took longer than usual for some reason which lead to a lot of confusion. 

I have had zero issues with rc4 though. It seems to work perfectly. Great work!

**Comment by mdias** [comment] 2022-10-06 15:01
Great to know!
In the meantime I have created a normal [0.6.3 release](https://github.com/mdias/rs_asio/releases/tag/v0.6.3) since more people reported good success as well.
I'm now closing this issue :)

**Closed by mdias** 2022-10-06 15:01 UTC
Labels: bug
