### ISSUE TITLE
RS asio is "not detecting game version"

### ISSUE THREAD

**Issue by Chimuu-KMT** [mdias/rs_asio#476] opened 2024-12-21 18:55 UTC
I'm not the only one that has de same problem, and its not just that. When I try to update the game to the previous version, the installation gets stuck on "starting download" or something like that. But when I install the current version of the game it downloads normally. Out clarify that I bought the game today with the new version. I hope someone can help me!

**Comment by mdias** [comment] 2024-12-21 23:46
Duplicate of #471

**Closed by mdias** 2024-12-21 23:46 UTC
