### ISSUE TITLE
Streaming with Discord crashes RS when using RS_ASIO

### ISSUE THREAD

**Issue by josephjoel64** [mdias/rs_asio#37] opened 2020-03-06 05:21 UTC
Title explains it all I think. Discord streaming breaks the game hard, alt-tabbing is broken even. Attached is my most recent log. Streaming screen only (i.e. not hooking audio) does not seem to cause issues. 

I have been able to make RS work with Discord streaming in the dark ages before RS_ASIO, and the fact that audio streaming is required to make it crash makes me think that it is surely an RS_ASIO issue.

Thanks for your work regardless. RS_ASIO has been amazing to use, especially now that I don't need to switch audio devices just to play a game. Being able to show a song to a friend occasionally would be a nice bonus :D 

[RS_ASIO-log.txt](https://github.com/mdias/rs_asio/files/4296542/RS_ASIO-log.txt)

**Comment by mdias** [comment] 2020-03-06 18:20
It should be very unliekly that RS_ASIO itself would be the cause of this, and it's more likely a driver issue. You can check this by opening another application that uses ASIO and try streaming that.

However, since you intend to stream, are you sure that your interface provides loopback audio? If so, you should select this audio source to stream. If not, then you probably want to use something like [Voicemeeter](https://www.vb-audio.com/Voicemeeter/banana.htm) so that you can create separate audio sources that replicate what the ASIO stream is outputing.

I'm not very familiar with discord streaming though, and only used OBS for streaming in the past, and it can work with RS_ASIO both using loopback features of my interface and/or using Voicemeeter.

**Comment by shadowtroop** [comment] 2020-03-09 23:54
I can tell you that at least a cursory check has shown that my music player, which is the only other ASIO application other than my DAWs, does not crash discord if I try to stream it.

I have exclusivity disabled wherever I can so I'm not sure what's up.

**Comment by mdias** [comment] 2020-03-12 21:37
Unfortunately I cannot reproduce the issue on my end. I can make it stream on discord, but I see no option on discord to select which audio input to use during streaming even, so I'm guessing it's only streaming video, as the audio is bypassing the windows sound system altogether.

**Comment by foxx1337** [comment] 2020-04-03 17:42
A better setup is to run RS 2014 with rs-asio and exclusivity and set the output to the device `Voicemeeter Virtual ASIO` which you get with [Voicemeeter](https://www.vb-audio.com/Voicemeeter/index.htm).

**Comment by shadowtroop** [comment] 2020-04-04 03:31
> A better setup is to run RS 2014 with rs-asio and exclusivity and set the output to the device Voicemeeter Virtual ASIO which you get with Voicemeeter.

Just tried it, still crashes with output set to Voicemeeter. Do I need to route the input through it as well?

**Comment by mdias** [comment] 2020-05-14 23:05
I'm closing this issue as I can't reproduce it and other users are also not having issues.
I've seen reports of similar crashes when Rocksmith is running in fullscreen, so maybe try running in windowed mode.
Other than that I can't offer any more ideas.

**Closed by mdias** 2020-05-14 23:05 UTC
Labels: Cannot reproduce
