### ISSUE TITLE
RS ASIO not detecting game version

### ISSUE THREAD

**Issue by FinSawatz** [mdias/rs_asio#473] opened 2024-12-21 05:09 UTC
I followed all the steps to the best of my ability, but upon checking the RS_ASIO-log.txt file I was given this log:

0.000 [INFO]   - Wrapper DLL loaded (v0.7.2)
0.000 [INFO]  PatchOriginalCode
0.064 [INFO]  image crc32: 0x6ea6d1ba
0.064 [ERROR]  Unknown game version
61.606 [INFO]   - Wrapper DLL unloaded

I downloaded the newest version of RS ASIO, copied the three files into the main directory of Rocksmith2014 as downloaded from Steam, and ran the game to initialize.

I am running Windows 11 Home 24H2.
I have a Focusrite Scarlett 2i2 4th gen.
I am using the USB asio drivers.

![image](https://github.com/user-attachments/assets/37333e31-9829-4dbb-b7e9-a8556a8f4b29)

This is what Steam reports as my game version. I uninstalled and reinstalled once already.

I know that the Scarlett 4th gen drivers have a known issue with being 64 bit only, but I'm taking this one step at a time. This issue seems to pertain to the game version itself and how RS ASIO is interfacing with it.

Thanks for any help anyone here can give!

**Comment by Thgear27** [comment] 2024-12-21 07:21
I've got the same problem. As you said, I also think it has something to do with the version released on Steam. Hopefully, they'll fix it soon :(

**Comment by dimitryustinov** [comment] 2024-12-21 12:01
use previous version of game
"Revert back to the working, pre-update version of RS2014. For those that don't know how to do this, right-click on RS in your Steam library, hit Properties. Under the "Betas" tab, enter the code **JustInCaseWeNeedIt** to revert back to the previous version. Let that download finish." Source - reddit
![Screenshot 2024-12-21 145003](https://github.com/user-attachments/assets/e31cc7db-ad1b-4e2b-af23-61bde593c12c)

**Comment by mfelipe** [comment] 2024-12-21 12:14
> use previous version of game
Should we keep using the previous version from now on or eventualy there will be a release to support it? Thanks!

**Comment by dimitryustinov** [comment] 2024-12-21 13:36
@mfelipe strange, it works for me, I'm using version 0.7.0 

`0.000 [INFO]   - Wrapper DLL loaded (v0.7.0)
0.000 [INFO]  PatchOriginalCode
0.232 [INFO]  image crc32: 0x21a8959a
0.573 [INFO]  Patching CoCreateInstance
0.573 [INFO]  Patch_CallAbsoluteIndirectAddress - num locations: 5
0.573 [INFO]  Patching call at 01C5AA85
0.573 [INFO]  Patching call at 01F03B6E
0.573 [INFO]  Patching call at 01F5C681
0.573 [INFO]  Patching call at 01FAEF75
0.573 [INFO]  Patching call at 01FAF40D
0.573 [INFO]  Patching PortAudio MarshalStreamComPointers
0.573 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.573 [INFO]  Patching call at 01F03059
0.573 [INFO]  Patching PortAudio UnmarshalStreamComPointers
0.573 [INFO]  Patch_CallRelativeAddress - num locations: 1
0.573 [INFO]  Patching call at 01F0310E
0.575 [INFO]  Patched_CoCreateInstance called: IID_IMMDeviceEnumerator
0.576 [INFO]  DebugDeviceEnum::GetDefaultAudioEndpoint - dataFlow: eRender - role: eMultimedia
0.576 [INFO]  RSAggregatorDeviceEnum::UpdateAvailableDevices
0.576 [INFO]  GetWineAsioInfo - Looking for wineasio.dll... 
0.578 [INFO]    Failed to load wineasio.dll or file not found
0.578 [INFO]  AsioHelpers::FindDrivers
0.580 [INFO]    ASIO4ALL v2
0.580 [INFO]    Focusrite Thunderbolt ASIO
0.580 [INFO]    Focusrite USB ASIO
0.581 [INFO]    Realtek ASIO
`

**Comment by dimitryustinov** [comment] 2024-12-21 13:51
@mfelipe I apologize for the misunderstanding, apparently the new build has its own "previous version" and in any case an update is needed for rs asio

**Comment by mdias** [comment] 2024-12-22 00:09
Duplicate of #471 .

I also found that the "previous_version" branch of this new build of the game is the same as the normal branch, so it also isn't working.

**Closed by mdias** 2024-12-22 00:09 UTC
