### ISSUE TITLE
M-Audio Fast Track 2 channel working

### ISSUE THREAD

**Issue by ColdDrip** [mdias/rs_asio#175] opened 2021-03-23 05:58 UTC
M-Audio Fast Track 2 channel works with this add on, however I'm still playingaround for the latency setting to remove crackling

Rocksmith config

```[Audio]
EnableMicrophone=0
ExclusiveMode=1
LatencyBuffer=3
ForceDefaultPlaybackDevice=
ForceWDM=0
ForceDirectXSink=0
DumpAudioLog=0
MaxOutputBufferSize=0
RealToneCableOnly=0
Win32UltraLowLatencyMode=1
```

RS_ASIO config
```
[Asio]
; available buffer size modes:
;    driver - respect buffer size setting set in the driver
;    host   - use a buffer size as close as possible as that requested by the host application
;    custom - use the buffer size specified in CustomBufferSize field
BufferSizeMode=driver
CustomBufferSize= 96

[Asio.Output]
Driver=Fast Track ASIO
BaseChannel=0
AltBaseChannel=
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.0]
Driver=Fast Track ASIO
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.1]
Driver=
Channel=1
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100

[Asio.Input.Mic]
Driver=Fast Track ASIO
Channel=0
EnableSoftwareEndpointVolumeControl=1
EnableSoftwareMasterVolumeControl=1
SoftwareMasterVolumePercent=100
```

**Comment by mdias** [comment] 2021-03-23 17:06
Thank you for the report.

I've edited your post a bit to improve formatting of the configs. I'm also closing the issue since latency config experience will vary from computer to computer even with the same interface.

Feel free to keep posting any information you think is helpful though, even if the issue is closed it might be useful to someone checking the interfaces list :)

**Closed by mdias** 2021-03-23 17:06 UTC

**Comment by Username-usersurname** [comment] 2021-04-24 12:43
Does it work with m audio fast track first revision?
